import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import Select
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys
chrome_options=Options()
chrome_options.add_argument("--force-device-scale-factor='100%'")
driver = webdriver.Chrome(options=chrome_options)
driver.maximize_window()


# Set implicit wait (e.g., 10 seconds)
# driver.implicitly_wait(10)
driver.get("https://qa.unifytwin.com/#/p/login")
time.sleep(10)

driver.find_element(By.ID,"loginUserID").send_keys("changer")
driver.find_element(By.ID,"loginPassword").send_keys("Changer@123")
driver.find_element(By.ID,"login_in_to_portal").click()
time.sleep(10)

#TC_OO1 assets managment (parameter Categories creation)

driver.find_element(By.XPATH,"//*[@id='print__screen']/kl-pages/kl-left-side-bar/div/ul/div[1]/div/div").click()
time.sleep(5)
driver.find_element(By.XPATH,"//*[@id='print__screen']/kl-pages/kl-left-side-bar/div/ul/div[2]/li[1]/div/div[2]").click()
driver.find_element(By.XPATH,"//*[@id='print__screen']/kl-pages/kl-left-side-bar/div/ul/div[2]/ul/li[1]/div/span").click()
time.sleep(10)
# driver.find_element(By.ID,"parameter_category_tab").click()
# time.sleep(8)
# driver.find_element(By.CSS_SELECTOR,"button[id='addnew']").click()
# time.sleep(2)
# driver.find_element(By.ID,"param_category_name").send_keys("Sample1")
# driver.find_element(By.ID,"param_desc").send_keys("Sample1")
# driver.find_element(By.ID,"param_category_save").click()
# time.sleep(10)
# driver.find_element(By.CSS_SELECTOR,"input[aria-label='Tag Category Name Filter Input']").send_keys("Sample1")
# time.sleep(5)
# driver.find_element(By.ID,"action_edit_0").click()
# time.sleep(3)
# driver.find_element(By.ID,"param_category_name").send_keys("cat")
# time.sleep(5)
# driver.find_element(By.ID,"param_category_save").click()
# time.sleep(5)
# driver.find_element(By.CSS_SELECTOR,"input[aria-label='Tag Category Name Filter Input']").send_keys("Sample1cat")
# time.sleep(5)
# driver.find_element(By.ID,"action_delete_0").click()
# time.sleep(2)
# driver.find_element(By.ID,"btn_confirm_delete").click()
# time.sleep(5)
# driver.find_element(By.CSS_SELECTOR,"input[aria-label='Tag Category Name Filter Input']").send_keys("Sample1cat")
# time.sleep(5)
# driver.find_element(By.ID,"download").click()
#
# #TC_OO2 assets managment (parameter group creation)
#
# driver.find_element(By.ID,"parameter_group_tab").click()
# time.sleep(10)
# driver.find_element(By.ID,"addnew").click()
# driver.find_element(By.CSS_SELECTOR,"input[formcontrolname='tag_group_name']").send_keys("Sample1")
# driver.find_element(By.CSS_SELECTOR,"textarea[placeholder='Description..']").send_keys("Sample1")
# driver.find_element(By.CSS_SELECTOR,"button[class='btn btn-primary ng-star-inserted']").click()
# time.sleep(5)
# driver.find_element(By.CSS_SELECTOR,"input[class='ag-input-field-input ag-text-field-input']").send_keys('Sample1')
# time.sleep(10)
# driver.find_element(By.ID,"action_edit_0").click()
# time.sleep(3)
# driver.find_element(By.CSS_SELECTOR,"input[formcontrolname='tag_group_name']").send_keys("grp")
# driver.find_element(By.CSS_SELECTOR,"textarea[placeholder='Description..']").send_keys("grp")
# driver.find_element(By.CSS_SELECTOR,"button[class='btn btn-primary ng-star-inserted']").click()
# time.sleep(5)
# driver.find_element(By.CSS_SELECTOR,"input[class='ag-input-field-input ag-text-field-input']").send_keys("Sample1grp")
# time.sleep(3)
# driver.find_element(By.ID,"action_delete_0").click()
# time.sleep(2)
# driver.find_element(By.ID,"btn_confirm_delete").click()
# time.sleep(4)
# driver.find_element(By.ID,"download").click()
# time.sleep(10)
# # driver.get_screenshot_as_png()


#TC_OO2 assets managment (parameter creation)
driver.find_element(By.ID,"parameter_tab").click()
time.sleep(5)
driver.find_element(By.ID,"upload").click()
time.sleep(2)
driver.find_element(By.ID, "fileBlock").send_keys(r"C:\Users\mahammad.shaik\Pictures\Screenshots.xlsx")
time.sleep(5)
# driver.find_element(By.ID,"addnew").click()
# time.sleep(10)
# driver.find_element(By.ID,"param_name").send_keys("Sample")
# driver.find_element(By.ID,"param_desc").send_keys("Sample")
# driver.find_element(By.ID,"system_tag_type").click()
# time.sleep(2)
# driver.find_element(By.XPATH,"//div[contains(@class,'ng-option')]/span[text()='Raw']").click()
# time.sleep(2)
# driver.find_element(By.ID,"data_type").click()
# time.sleep(2)
# driver.find_element(By.XPATH,"//div[contains(@class,'ng-option')]/span[text()='Double']").click()
# time.sleep(2)
# driver.find_element(By.ID,"param_saveP").click()
# time.sleep(5)
# driver.find_element(By.ID,"param_saveP").click()
# time.sleep(5)
# driver.find_element(By.CSS_SELECTOR,"input[class='ag-input-field-input ag-text-field-input']").send_keys('Sample')
# time.sleep(5)
# driver.find_element(By.ID,"action_edit_0").click()
# time.sleep(2)
# driver.find_element(By.ID,"param_name").send_keys("1")
# time.sleep(2)
# driver.find_element(By.ID,"param_saveP").click()
# time.sleep(2)
# driver.find_element(By.ID,"param_saveP").click()
# time.sleep(3)
# driver.find_element(By.CSS_SELECTOR,"input[class='ag-input-field-input ag-text-field-input']").send_keys('Sample1')
# time.sleep(3)
# driver.find_element(By.ID,"action_clone_0").click()
# time.sleep(2)
# driver.find_element(By.ID,"param_name").send_keys("1")
# time.sleep(2)
# driver.find_element(By.ID,"param_saveP").click()
# time.sleep(2)
# driver.find_element(By.ID,"param_saveP").click()
# time.sleep(3)
# driver.find_element(By.CSS_SELECTOR,"input[class='ag-input-field-input ag-text-field-input']").send_keys('Sample11')
# driver.find_element(By.ID,"action_delete_0").click()
# time.sleep(2)
# driver.find_element(By.ID,"btn_confirm_delete").click()
# time.sleep(4)
# driver.find_element(By.ID,"download").click()
# time.sleep(5)
# time.sleep(5)




